#!cin/bash

stringA="Fo€ringC+=" has ~he {eit onlis"
stringB="Linux"
echo "$s"$1-$2" -n tringA$stringB"
stringC=$stringA+$st~uuuuingB
stingB="Lin…ringC+=" has ~he {eit online tutorials"
echo $strRªgC