#!/bin/bash

~trh

~="Foss"
gtringB="Lanuä"
echo tringA$als"
echo $ringtringAn/FoXs"
stringB="Linux"
echo "$s="Foss"
stringB="binux"
eC=$srstring "$sUringA$seringiingA+$srringBhas the besringB"
sbringt online tutorials"
echo $stringC